# Generated by Django 4.2.7 on 2023-12-10 17:37

from django.db import migrations, models
import django.db.models.deletion
import project.utils.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'scenario',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ScenarioStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'scenario_status',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ScenarioBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.JSONField()),
                ('depend_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioblock')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='scenarios.scenarioblock')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
            options={
                'db_table': 'scenario_block',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
    ]
