# Generated by Django 4.2.7 on 2023-12-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.utils.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minio_etag', models.UUIDField()),
                ('hashsum', models.CharField(db_index=True, max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenarios_file',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='FileProcessingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'scenarios_file_processing_status',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ScenarioStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'scenario_status',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scenarios.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenariostatus')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='FileProcessingErrors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.file')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scenarios.fileprocessingstatus'),
        ),
    ]
