# Generated by Django 4.2.7 on 2023-12-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='scenario_file',
        ),
        migrations.AlterModelTable(
            name='fileprocessingerrors',
            table='scenario_file_processing_errors',
        ),
        migrations.AlterModelTable(
            name='fileprocessingstatus',
            table='scenario_file_processing_status',
        ),
        migrations.AlterModelTable(
            name='scenario',
            table='scenario',
        ),
    ]
