# Generated by Django 4.2.7 on 2023-12-03 15:15

from django.db import migrations, models
import django.db.models.deletion
import project.utils.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_file_table_alter_fileprocessingerrors_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('depend_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioblock')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
            options={
                'db_table': 'scenario_block',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
    ]
