# Generated by Django 4.2.7 on 2023-12-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_scenarioblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='scenarios.file'),
        ),
    ]
