# Generated by Django 4.2.7 on 2023-12-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_type_alter_scenario_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
