# Generated by Django 4.2.7 on 2023-12-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0008_scenarioblock_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioblock',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
