FROM node:16-slim as front_builder
WORKDIR /app

COPY frontend .
RUN yarn
RUN yarn build


FROM ubuntu:22.04

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH=$PATH:/root/.local/bin

WORKDIR /usr/src/app
RUN apt update -y && \
    apt install -y curl wget nmap \
    nginx tmux redis-server python3 python3-pip vim \
    net-tools openssh-client openssh-server sqlmap

COPY --from=front_builder /app/dist /var/www/dist

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./manage.py .
COPY ./config ./config
COPY ./project ./project
COPY ./mdm_db.sqlite3 .
COPY .env .
COPY ./default /etc/nginx/sites-enabled/default
COPY docker-start.sh .

ENTRYPOINT ["bash", "docker-start.sh"]
