# Generated by Django 4.2.5 on 2023-09-14 16:00

from django.db import migrations


def forward(apps, schema_editor):
    UserRole = apps.get_model('users', 'UserRole')

    roles = (
        UserRole(
            name="Администратор",
            code="ADMINISTRATOR",
            priority=100
        ),
        UserRole(
            name="Оператор",
            code="OPERATOR",
            priority=10
        ),
        UserRole(
            name="Пользователь",
            code="USER",
            priority=0
        ),
    )
    UserRole.objects.bulk_create(roles, ignore_conflicts=True)


def backward(apps, schema_editor):
    UserRole = apps.get_model('users', 'UserRole')
    UserRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]