# Generated by Django 4.2.7 on 2023-12-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.utils.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0003_scenarioblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
            options={
                'db_table': 'process',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'process_status',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
                ('scenario_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioblock')),
            ],
            options={
                'db_table': 'process_trigger',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessTriggerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.processtrigger')),
            ],
            options={
                'db_table': 'process_trigger_message',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'db_table': 'process_message',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processes.processstatus'),
        ),
    ]
