# Generated by Django 4.2.7 on 2023-12-10 17:37

from django.db import migrations, models
import django.db.models.deletion
import project.utils.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'process',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'process_message',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'process_status',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process')),
            ],
            options={
                'db_table': 'process_trigger',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
        migrations.CreateModel(
            name='ProcessTriggerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.processtriggermessage')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.processtrigger')),
            ],
            options={
                'db_table': 'process_trigger_message',
            },
            bases=(models.Model, project.utils.models.mixins.PkUUIDModelMixin),
        ),
    ]
