# Generated by Django 4.2.7 on 2023-12-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtrigger',
            name='scenario_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenarioblock'),
        ),
        migrations.AddField(
            model_name='processmessage',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.process'),
        ),
    ]
