# Generated by Django 4.2.7 on 2023-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
