# Generated by Django 4.2.7 on 2023-12-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_alter_process_owner_alter_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtrigger',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
