# Generated by Django 4.2.7 on 2023-12-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_alter_processtrigger_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtriggermessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.processtriggermessage'),
        ),
    ]
